<?php
/**
 * Created by PhpStorm.
 * User: tturner
 * Date: 2/24/2018
 * Time: 7:29 PM
 */

class cardInfo
{
	public $xmf = array(
		'Beast',
		'Beast',
		'Beast',
		'Black Tom Cassidy',
		'Black Tom Cassidy',
		'Blob',
		'Blob',
		'Cerebra',
		'Cerebra',
		'Cerebra',
		'Cyclops',
		'Cyclops',
		'Donald Pierce',
		'Donald Pierce',
		'Donald Pierce',
		'Emma Frost',
		'Emma Frost',	
		'Emma Frost',
		'Hope Summers',
		'Hope Summers',
		'Hope Summers',
		'Iceman',
		'Iceman',
		'Jean Grey',
		'Jean Grey',
		'Jubilee',
		'Jubilee',
		'Jubilee',
		'Kitty Pryde',
		'Kitty Pryde',
		'Kitty Pryde',
		'Lady Deathstrike',
		'Lady Deathstrike',
		'Lady Deathstrike',
		'Madelyne Pryor',
		'Madelyne Pryor',
		'Madelyne Pryor',
		'Magneto',
		'Magneto',
		'Mastermind',
		'Mastermind',
		'Mastermind',
		'Mystique',
		'Mystique',
		'Mystique',
		'Professor X',
		'Professor X',
		'Professor X',
		'Rachel Summers',
		'Rachel Summers',
		'Rachel Summers',
		'Sabretooth',
		'Sabretooth',
		'Sebastian Shaw',
		'Sebastian Shaw',
		'Storm',
		'Storm',
		'Storm',
		'Toad',
		'Toad',
		'Wolverine',
		'Wolverine',
		'Brave Sacrifice',
		'Counterstrike',
		'Dual Defense',
		'Invulnerability',
		'Reinforecements',
		'Replenish',
		'Teamwork',
		'Too Big To Fly',
		'Way Out West',
		'Whoever Assemble!'
	);
	
    public $xfo = array(
        'Cable',
		'Cable',
		'Cable',
        'Dani Moonstar',
		'Dani Moonstar',
		'Dani Moonstar',
		'Deadpool',
		'Deadpool',
		'Deadpool',
		'Domino',
		'Domino',
		'Domino',
		'Fantomex',
		'Fantomex',
		'Fantomex',
		'Forge',
		'Forge',
		'Forge',
		'Magik',
		'Magik',
		'Magik',
		'Psylocke',
		'Psylocke',
		'Psylocke'
     );
     
	public $dxm = array(
        'Blink',
		'Blink',
		'Blink',
		'Dark Beast',
		'Dark Beast',
		'Dark Beast',
		'Mimic',
		'Mimic',
		'Mimic',
		'Polaris',
		'Polaris',
		'Polaris',
		'Rogue',
		'Rogue',
		'Rogue',
		'Sage',
		'Sage',
		'Sage',
		'Sunspot',
		'Sunspot',
		'Sunspot',
		'Thunderbird',
		'Thunderbird',
		'Thunderbird'
     );
	 
	public $m2019_dice =  array( 'ai', 'ai', 'smc', 'smc', 'thor', 'thor', 'thor', 'imw');
    public $m2019 =  array(
    'Black Widow',
    'Captain America',
    'Spider-Man',
    'Black Cat',
    'Kate Bishop',
    'Vision',
    'Iron Man',
    'War Machine'
	);

	public $jus = array(
		'Aquaman',
		'Aquaman',
		'Aquaman',
		'Batman',
		'Batman',
		'Batman',
		'Bizarro',
		'Bizarro',
		'Black Manta',
		'Black Manta',
		'Black Manta',
		'Brainiac',
		'Brainiac',
		'Clayface',
		'Clayface',
		'Clayface',
		'Gorilla Grodd',
		'Gorilla Grodd',
		'Gorilla Grodd',
		'Green Lantern',
		'Green Lantern',
		'Green Lantern',
		'Hall of Doom',
		'Hall of Doom',
		'Lex Luthor',
		'Lex Luthor',
		'Martian Manhunter',
		'Martian Manhunter',
		'Metallo',
		'Metallo',
		'Metallo',
		'Parasite',
		'Parasite',
		'Parasite',
		'Poison Ivy',
		'Poison Ivy',
		'Poison Ivy',
		'Scarecrow',
		'Scarecrow',
		'Scarecrow',
		'Solomon Grundy',
		'Solomon Grundy',
		'Superman',
		'Superman',
		'The Atom',
		'The Atom',
		'The Atom',
		'The Flash',
		'The Flash',
		'The Flash',
		'The Joker',
		'The Joker',
		'The Riddler',
		'The Riddler',
		'Toyman',
		'Toyman',
		'Toyman',
		'Watchtower',
		'Watchtower',
		'Watchtower',
		'Wonder Woman',
		'Wonder Woman',
		'Wonder Woman',
		'Betrayal',
		'Doom Lance',
		'Energy Field',
		'Excessive Force',
		'Investigation',
		'Ping',
		'Power Almighty',
		'Static Field',
		'Stretch',
		'Suffering and Satisfaction'
	);
	
    public $doom = array(
        'Beast Boy',
		'Beast Boy',
		'Beast Boy',
        'Black Canary',
		'Black Canary',
		'Black Canary',
		'Elasti-Girl',
		'Elasti-Girl',
		'Elasti-Girl',
		'Green Arrow',
		'Green Arrow',
		'Green Arrow',
		'Hawkman',
		'Hawkman',
		'Hawkman',
		'Negative Man',
		'Negative Man',
		'Negative Man',
		'Plastic Man',
		'Plastic Man',
		'Plastic Man',
		'Robotman',
		'Robotman',
		'Robotman'
     );
     
	public $myst = array(
        'Atlantis',
		'Atlantis',
		'Atlantis',
		'Black Adam',
		'Black Adam',
		'Black Adam',
		'Freddy Freeman',
		'Freddy Freeman',
		'Freddy Freeman',
		'Mary Marvel',
		'Mary Marvel',
		'Mary Marvel',
		'Phantom Stranger',
		'Phantom Stranger',
		'Phantom Stranger',
		'Shazam',
		'Shazam',
		'Shazam',
		'Yellow Lantern Ring',
		'Yellow Lantern Ring',
		'Yellow Lantern Ring',
		'Zatanna',
		'Zatanna',
		'Zatanna'
     );

   public $bfu = array(
   'Foetid Bloat-Drone',
   'Foetid Bloat-Drone',
   'Foetid Bloat-Drone',
   'Lord of Contagion',
   'Lord of Contagion',
   'Lord of Contagion',
   'Malignant Plaguecaster',
   'Malignant Plaguecaster',
   'Malignant Plaguecaster',
   'Mortarion',
   'Mortarion',
   'Mortarion',
   'Noxious Blightbringer',
   'Noxious Blightbringer',
   'Noxious Blightbringer',
   'Plague Marine',
   'Plague Marine',
   'Plague Marine',
   'Poxwalker',
   'Poxwalker',
   'Poxwalker',
   'Primaris Inceptor',
   'Primaris Inceptor',
   'Primaris Inceptor',
   'Primaris Intercessor',
   'Primaris Intercessor',
   'Primaris Intercessor',
   'Primaris Redemptor Dreadnought',
   'Primaris Redemptor Dreadnought',
   'Primaris Redemptor Dreadnought',
   'Primaris Reiver',
   'Primaris Reiver',
   'Primaris Reiver',
   'Primaris Repulsor', 
   'Primaris Repulsor', 
   'Primaris Repulsor', 
   'Primaris Aggressor', 
   'Primaris Aggressor', 
   'Primaris Aggressor',
   'Roboute Guilliman',
   'Roboute Guilliman',
   'Roboute Guilliman',
   'Typhus',
   'Typhus',
   'Typhus',
   'Varro Tigurius',
   'Varro Tigurius',
   'Varro Tigurius',
   'Bolter Drill',
   'Chaos Warp',
   'Excessive Ordinance',
   'Instant War',
   'Into Battle!',
   'Might of the Astartes',
   'Orbital Strike',
   'Rolling Thunder',
   'Seething',
   'Static Field'
);

   public $ork = array(
   'Battlewagon',
   'Battlewagon',
   'Battlewagon',
   'Ghazghkul Thraka',
   'Ghazghkul Thraka',
   'Ghazghkul Thraka',
   'Mogrok',
   'Mogrok',
   'Mogrok',
   'Ork Boy',
   'Ork Boy',
   'Ork Boy',
   'Ork Nob',
   'Ork Nob',
   'Ork Nob',
   'Stompa',
   'Stompa',
   'Stompa',
   'Stormboyz',
   'Stormboyz',
   'Stormboyz',
   'Warbiker',
   'Warbiker',
   'Warbiker'
);

   public $sw = array(
   'Grey Hunter',
   'Grey Hunter',
   'Grey Hunter',
   'Logan Grimnar',
   'Logan Grimnar',
   'Logan Grimnar',
   'Sky Claw',
   'Sky Claw',
   'Sky Claw',
   'Space Wolf Predator',
   'Space Wolf Predator',
   'Space Wolf Predator',
   'Thunderwolf Cavalry',
   'Thunderwolf Cavalry',
   'Thunderwolf Cavalry',
   'Venerable Dreadnaught',
   'Venerable Dreadnaught',
   'Venerable Dreadnaught',
   'Wolf Guard Terminator',
   'Wolf Guard Terminator',
   'Wolf Guard Terminator',
   'Wulfen',
   'Wulfen',
   'Wulfen'
);

   public $hq =  array(
   'Batman',
   'Batman',
   'Batman',
   'Catwoman',
   'Catwoman',
   'Catwoman',
   'DeadShot',
   'DeadShot',
   'Harley Quinn',
   'Harley Quinn',
   'Harley Quinn',
   'Harley\'s Hyena',
   'Harley\'s Hyena',
   'Harley\'s Hyena',
   'Poison Ivy',
   'Poison Ivy',
   'Poison Ivy',
   'Power Girl',
   'Power Girl',
   'The Joker',
   'The Joker',
   'Relaxing',
   'Target Lock',
   'Thrown Brick',
);

	public $ki = array(
	'Drax',
	'Drax',
	'Drax',
	'Groot',
	'Groot',
	'Groot',
	'Kree Captain',
	'Kree Captain',
	'Kree Captain',
	'Kree Soldier',
	'Kree Soldier',
	'Kree Soldier',
	'Mantis',
	'Mantis',
	'Mantis',
	'Rocket Raccoon',
	'Rocket Raccoon',
	'Rocket Raccoon',
	'Supreme Intelligence',
	'Supreme Intelligence',
	'Supreme Intelligence',
	'Thanos',
	'Thanos',
	'Thanos',
);

public $jll = array(
	'Ant-man',
	'Ant-man',
	'Ant-man',
	'Atlas',
	'Atlas',
	'Atlas',
	'Citizen V',
	'Citizen V',
	'Citizen V',
	'Hawkeye',
	'Hawkeye',
	'Hawkeye',
	'MACH-1',
	'MACH-1',
	'MACH-1',
	'Meteorite',
	'Meteorite',
	'Meteorite',
	'Songbird',
	'Songbird',
	'Songbird',
	'Techno',
	'Techno',
	'Techno',
);

    public $ai =  array(
    'Arnim Zola',
	'Arnim Zola',
	'Arnim Zola',
	'Avengers ID Cards',
	'Avengers ID Cards',
	'Avengers ID Cards',
	'Black Panther',
	'Black Panther',
	'Black Panther',
	'Black Widow',
	'Black Widow',
	'Black Widow',
	'Captain America',
	'Captain America',
	'Captain America',
	'Doctor Strange',
	'Doctor Strange',
	'Doctor Strange',
	'Dormammu',
	'Dormammu',
	'Dormammu',
	'Gamora',
	'Gamora',
	'Gamora',
	'Hulk',
	'Hulk',
	'Hulk',
	'Iron Man',
	'Iron Man',
	'Iron Man',
	'Loki',
	'Loki',
	'Loki',
	'Red Skull',
	'Red Skull',
	'Red Skull',
	'Star-Lord',
	'Star-Lord',
	'Star-Lord',
	'Thor',
	'Thor',
	'Thor',
	'Vision',
	'Vision',
	'Vision',
	'Wasp',
	'Wasp',
	'Wasp',
	'Big Entrance',
	'Blam! Blam! Blam!',
	'Confront The Mighty',
	'Crowd Fighting',
	'I Want You!',
	'Raised Shields',
	'Squad Goals',
	'Take Cover',
	'Under Surveillance',
	'Wormhole',
);
   
    // Dice / Genders
    public $thor = array(
    'Archnemesis',
    'Big Entrance',
    'Don the Helm',
    'Flying Hammer',
    'Get Thee Hence',
    'Investigation',
    'Midgard',
    'Odin\'s Fury',
    'Released from the Ice',
    'Shockwave',
    'Surprise Attack',
    'Villainous Pact',
    'Absorbing Man',
    'Balder',
    'Beta Ray Bill',
    'Billy Club',
    'Blackheart',
    'Chipmunk Hunk',
    'Crystal',
    'Daredevil',
    'Destroyer',
    'Enchantress',
    'Fandral',
    'Heimdall',
    'Hela',
    'Hogun',
    'Hulk',
    'Iron Man',
    'Jane Foster',
    'Jarnbjorn',
    'Karnak',
    'Kate Bishop',
    'Loki',
    'Malekith',
    'Mjolnir',
    'Mr. Fixit',
    'Nick Fury',
    'Odin',
    'Pepper Potts',
    'Punisher',
    'Ragnarok',
    'SP//dr',
    'Samantha Wilson',
    'Sif',
    'Surtur',
    'The Bifrost',
    'Thor (M)',
    'Thor (F)',
    'Thorbuster Iron Man',
    'US Agent',
    'Volstagg',
    'Wrecker',
    'Absorbing Man',
    'Balder',
    'Beta Ray Bill',
    'Billy Club',
    'Blackheart',
    'Chipmunk Hunk',
    'Crystal',
    'Daredevil',
    'Destroyer',
    'Enchantress',
    'Fandral',
    'Heimdall',
    'Hela',
    'Hogun',
    'Hulk',
    'Iron Man',
    'Jane Foster',
    'Jarnbjorn',
    'Karnak',
    'Kate Bishop',
    'Loki',
    'Malekith',
    'Mjolnir',
    'Mr. Fixit',
    'Nick Fury',
    'Odin',
    'Pepper Potts',
    'Punisher',
    'Ragnarok',
    'SP//dr',
    'Samantha Wilson',
    'Sif',
    'Surtur',
    'The Bifrost',
    'Thor (M)',
    'Thor (F)',
    'Thorbuster Iron Man',
    'US Agent',
    'Volstagg',
    'Wrecker',
    'Absorbing Man',
    'Balder',
    'Beta Ray Bill',
    'Billy Club',
    'Blackheart',
    'Chipmunk Hunk',
    'Crystal',
    'Daredevil',
    'Destroyer',
    'Enchantress',
    'Fandral',
    'Heimdall',
    'Hela',
    'Hogun',
    'Hulk',
    'Iron Man',
    'Jane Foster',
    'Jarnbjorn',
    'Karnak',
    'Kate Bishop',
    'Loki',
    'Mjolnir',
    'Mr. Fixit',
    'Nick Fury',
    'Odin',
    'Pepper Potts',
    'Punisher',
    'SP//dr',
    'Samantha Wilson',
    'Sif',
    'Surtur',
    'The Bifrost',
    'Thorbuster Iron Man',
    'US Agent',
    'Volstagg',
    'Wrecker',
    'Malekith',
    'Ragnarok',
    'Thor (F)',
    'Thor (M)',
    'Earth X Captain America',
    'Earth X Machine Man',
    'Earth X The Skull',
    'Earth X Thor',
);




    //BEGIN TOA Promo -OP
    //public $dd_op2017_dice =  array( 'dp', 'dp', 'dp', 'dp', 'dp', 'dp');
    //public $dd_op2017 =  array(


    //BEGIN Tomb of Annihilation
    public $toa =  array(
    'Burning Hands',
    'Candlekeep',
    'Cone of Cold',
    'Create Food and Water',
    'Guardian of Faith',
    'Heavy Armor',
    'Heist',
    'Holy Avenger',
    'Improvised Weapon',
    'Insect Plague',
    'Magic Missile',
    'Scorching Ray',
    'Aasimar Paladin',
    'Acererak',
    'Allosaurus',
    'Amber Golem',
    'Artus Cimber',
    'Basilisk',
    'Batiri Battle Stack',
    'Birdsong',
    'Captain Elok Jaharwon',
    'Captain Laskilar',
    'Chwinga',
    'Doppelganger',
    'Dragon Statue Trap',
    'Dragonborn Sorcerer',
    'Elf Druid',
    'Fenthaza',
    'Frost Giant',
    'Gold Dragon',
    'Goliath Fighter',
    'Green Devil Mask',
    'Human Outlander',
    'Kobold Trap',
    'Poison Dart Trap',
    'Pseudodragon',
    'Queen Grabstab',
    'Ras Nsi',
    'Red Dragon',
    'Silver Dragon',
    'Skeleton Key',
    'Stone Golem',
    'Tabaxi Rogue',
    'Tomb Dwarf',
    'Tomb Guardian',
    'Triceratops',
    'Tyrannosaurus Zombie',
    'Valindra Shadowmantle',
    'Xandala Cimber',
    'Yuan-ti Abomination',
    'Yuan-ti Pureblood',
    'Zombie',
    'Aasimar Paladin',
    'Acererak',
    'Allosaurus',
    'Amber Golem',
    'Artus Cimber',
    'Basilisk',
    'Batiri Battle Stack',
    'Birdsong',
    'Captain Elok Jaharwon',
    'Captain Laskilar',
    'Chwinga',
    'Doppelganger',
    'Dragon Statue Trap',
    'Dragonborn Sorcerer',
    'Elf Druid',
    'Fenthaza',
    'Frost Giant',
    'Gold Dragon',
    'Goliath Fighter',
    'Green Devil Mask',
    'Human Outlander',
    'Kobold Trap',
    'Poison Dart Trap',
    'Pseudodragon',
    'Queen Grabstab',
    'Ras Nsi',
    'Red Dragon',
    'Silver Dragon',
    'Skeleton Key',
    'Stone Golem',
    'Tabaxi Rogue',
    'Tomb Dwarf',
    'Tomb Guardian',
    'Triceratops',
    'Tyrannosaurus Zombie',
    'Valindra Shadowmantle',
    'Xandala Cimber',
    'Yuan-ti Abomination',
    'Yuan-ti Pureblood',
    'Zombie',
    'Aasimar Paladin',
    'Acererak',
    'Allosaurus',
    'Amber Golem',
    'Artus Cimber',
    'Basilisk',
    'Batiri Battle Stack',
    'Birdsong',
    'Captain Elok Jaharwon',
    'Captain Laskilar',
    'Chwinga',
    'Dragon Statue Trap',
    'Dragonborn Sorcerer',
    'Elf Druid',
    'Fenthaza',
    'Frost Giant',
    'Gold Dragon',
    'Goliath Fighter',
    'Green Devil Mask',
    'Human Outlander',
    'Kobold Trap',
    'Poison Dart Trap',
    'Pseudodragon',
    'Queen Grabstab',
    'Ras Nsi',
    'Red Dragon',
    'Silver Dragon',
    'Skeleton Key',
    'Stone Golem',
    'Tabaxi Rogue',
    'Tomb Dwarf',
    'Tomb Guardian',
    'Tyrannosaurus Zombie',
    'Xandala Cimber',
    'Yuan-ti Abomination',
    'Zombie',
    'Doppelganger',
    'Triceratops',
    'Valindra Shadowmantle',
    'Yuan-ti Pureblood',
    'Kir Sabal',
    'Ring of Winter',
    'Staff of the Forgotten One',
    'The Soulmonger',
    'Brazen Pegasus',
);

    public $xfc =  array(
    'Angel',
    'Avalanche',
    'Banshee',
    'Beast',
    'Bishop',
    'Blink',
    'Blob',
    'Boom Boom',
    'Colossus',
    'Cyclops',
    'Danger Room',
    'Doop',
    'Emma Frost',
    'Havok',
    'Iceman',
    'Jean Grey',
    'Jubilee',
    'Juggernaut',
    'Kitty Pryde',
    'Magneto',
    'Mimic',
    'Morph',
    'Nocturne',
    'Onslaught',
    'Polaris',
    'Professor X',
    'Pyro',
    'Quicksilver',
    'Sabretooth',
    'Sasquatch',
    'Scarlet Witch',
    'Sebastian Shaw',
    'Sentinel',
    'Storm',
    'Sunfire',
    'The Blackbird',
    'The Hellfire Club',
    'Thunderbird',
    'Wolverine',
    'Xavier\'s School',
    'Angel',
    'Avalanche',
    'Banshee',
    'Beast',
    'Bishop',
    'Blink',
    'Blob',
    'Boom Boom',
    'Colossus',
    'Cyclops',
    'Danger Room',
    'Doop',
    'Emma Frost',
    'Havok',
    'Iceman',
    'Jean Grey',
    'Jubilee',
    'Juggernaut',
    'Kitty Pryde',
    'Magneto',
    'Mimic',
    'Morph',
    'Nocturne',
    'Onslaught',
    'Polaris',
    'Professor X',
    'Pyro',
    'Quicksilver',
    'Sabretooth',
    'Sasquatch',
    'Scarlet Witch',
    'Sebastian Shaw',
    'Sentinel',
    'Storm',
    'Sunfire',
    'The Blackbird',
    'The Hellfire Club',
    'Thunderbird',
    'Wolverine',
    'Xavier\'s School',
    'Angel',
    'Avalanche',
    'Banshee',
    'Beast',
    'Bishop',
    'Blink',
    'Blob',
    'Colossus',
    'Cyclops',
    'Danger Room',
    'Doop',
    'Havok',
    'Iceman',
    'Jean Grey',
    'Juggernaut',
    'Kitty Pryde',
    'Magneto',
    'Morph',
    'Nocturne',
    'Onslaught',
    'Polaris',
    'Professor X',
    'Pyro',
    'Quicksilver',
    'Sabretooth',
    'Sasquatch',
    'Scarlet Witch',
    'Sebastian Shaw',
    'Sentinel',
    'Storm',
    'Sunfire',
    'The Blackbird',
    'The Hellfire Club',
    'Thunderbird',
    'Wolverine',
    'Xavier\'s School',
    'Boom Boom',
    'Emma Frost',
    'Jubilee',
    'Mimic',
    'Blink In-Betweener',
    'Cosmic X-23',
    'Czar Colossus',
    'Phoenix Storm'
);
    //END X-Men First Class Hack

    public $gotg =  array(
    'Adam Warlock',
    'Agent Venom',
    'Angela',
    'Beta Ray Bill',
    'Black Widow',
    'Captain America',
    'Captain Marvel',
    'Cosmic Cube',
    'Cosmo Space Dog',
    'Daisy Johnson',
    'Drax',
    'Dum Dum Dugan',
    'Gamora',
    'Ghost Rider',
    'Groot',
    'Hulk',
    'Ironheart',
    'Knowhere',
    'Madame Masque',
    'Madame Web',
    'Mantis',
    'Moondragon',
    'Nebula',
    'Norman Osborn',
    'Nova Corps Uniform',
    'Nova Prime',
    'Quasar',
    'Ricochet',
    'Rocket Raccoon',
    'Ronan the Accuser',
    'S.W.O.R.D. Agent',
    'Squirrel Girl',
    'Star-Lord',
    'Stick',
    'Thanos',
    'The Collector',
    'The Kyln',
    'The Spot',
    'Yellowjacket',
    'Yondu',
    'Adam Warlock',
    'Agent Venom',
    'Angela',
    'Beta Ray Bill',
    'Black Widow',
    'Captain America',
    'Captain Marvel',
    'Cosmic Cube',
    'Cosmo Space Dog',
    'Daisy Johnson',
    'Drax',
    'Dum Dum Dugan',
    'Gamora',
    'Ghost Rider',
    'Groot',
    'Hulk',
    'Ironheart',
    'Knowhere',
    'Madame Masque',
    'Madame Web',
    'Mantis',
    'Moondragon',
    'Nebula',
    'Norman Osborn',
    'Nova Corps Uniform',
    'Nova Prime',
    'Quasar',
    'Ricochet',
    'Rocket Raccoon',
    'Ronan the Accuser',
    'S.W.O.R.D. Agent',
    'Squirrel Girl',
    'Star-Lord',
    'Stick',
    'Thanos',
    'The Collector',
    'The Kyln',
    'The Spot',
    'Yellowjacket',
    'Yondu',
    'Adam Warlock',
    'Agent Venom',
    'Beta Ray Bill',
    'Black Widow',
    'Captain Marvel',
    'Cosmic Cube',
    'Cosmo Space Dog',
    'Daisy Johnson',
    'Drax',
    'Dum Dum Dugan',
    'Gamora',
    'Ghost Rider',
    'Groot',
    'Hulk',
    'Ironheart',
    'Knowhere',
    'Madame Masque',
    'Madame Web',
    'Mantis',
    'Moondragon',
    'Nebula',
    'Nova Corps Uniform',
    'Nova Prime',
    'Quasar',
    'Ricochet',
    'Rocket Raccoon',
    'Ronan the Accuser',
    'S.W.O.R.D. Agent',
    'Squirrel Girl',
    'Stick',
    'Thanos',
    'The Collector',
    'The Kyln',
    'The Spot',
    'Yellowjacket',
    'Yondu',
    'Angela',
    'Captain America',
    'Norman Osborn',
    'Star-Lord',
    'Captain Britain Iron Man',
    'Groot Thor',
    'King Black Bolt',
    'Punisher Sorcerer Supreme',
);
    public $smc =  array(
    'Black Cat',
    'Black Cat',
    'Black Cat',
    'Captain America',
    'Captain America',
    'Captain America',
    'Carnage',
    'Carnage',
    'Carnage',
    'Doppelganger',
    'Doppelganger',
    'Doppelganger',
    'Iron Fist',
    'Iron Fist',
    'Iron Fist',
    'Shriek',
    'Shriek',
    'Shriek',
    'Spider-Man',
    'Spider-Man',
    'Spider-Man',
    'Venom',
    'Venom',
    'Venom',
);
    public $sww =  array(
    'Artemis',
    'Artemis',
    'Artemis',
    'Cheetah',
    'Cheetah',
    'Cheetah',
    'Giganta',
    'Giganta',
    'Giganta',
    'Jimmy Olsen',
    'Jimmy Olsen',
    'Jimmy Olsen',
    'Steve Trevor',
    'Steve Trevor',
    'Steve Trevor',
    'Supergirl',
    'Supergirl',
    'Supergirl',
    'Superman',
    'Superman',
    'Superman',
    'Wonder Woman',
    'Wonder Woman',
    'Wonder Woman',
    'Dimension Door',
    'Misdirection',
    'Plot Twist',
    'Resurrection',
    'Save Civilians',
    'Small Step For Man',
    'Take Cover',
    'Team Up',
    'The Outsider',
    'Truce',
);

    public $dc2017 =  array(
    'Batman™',
    'Robin™',
    'The Joker™',
    'The Riddler™',
    'Talia al Ghul™',
    'Catwoman™',
    'Poison Ivy™',
);

    public $m2017_dice =  array( 'dp', 'dp', 'dp', 'dp','dp','dp','xfc','aou','','avx','xfc');
    public $m2017 =  array(
    // DP dice
    'Deadpool',
    'Lady Deadpool',
    'Colossus',
    'Wolverine',
    'Lockjaw',
    'Medusa',
    'Morph',
    'Sabretooth',
    'Groot',
    'Power Bolt',
    'Mystique',
    'Magneto',
);

    public $def =  array(
    'Clea',
    'Clea',
    'Clea',
    'Doctor Strange',
    'Doctor Strange',
    'Doctor Strange',
    'Hellcat',
    'Hellcat',
    'Hellcat',
    'Hulk',
    'Hulk',
    'Hulk',
    'Iron Fist',
    'Iron Fist',
    'Iron Fist',
    'Jessica Jones',
    'Jessica Jones',
    'Jessica Jones',
    'Loki',
    'Loki',
    'Loki',
    'Luke Cage',
    'Luke Cage',
    'Luke Cage',
);

    public $bat =  array(
    'Ace the Bat Hound™',
    'Bane™',
    'Bat-Signal™',
    'Batarang™',
    'Batgirl™',
    'Batman™',
    'Batwoman™',
    'Big Barda™',
    'Catwoman™',
    'Commissioner Gordon™',
    'Conner Kent™',
    'Darkseid™',
    'Dove™',
    'Firefly™',
    'Harley Quinn™',
    'Hawk™',
    'Hawkgirl™',
    'Huntress™',
    'Hush™',
    'Jervis Tetch™',
    'Killer Croc™',
    'Mister Miracle™',
    'Mr. Freeze™',
    'Nightwing™',
    'Orion™',
    'Owlman™',
    'Parademon™',
    'Ra\'s Al Ghul™',
    'Red Hood™',
    'Rip Hunter™',
    'Robin™',
    'Talia al Ghul™',
    'The Joker™',
    'The Penguin™',
    'The Question™',
    'The Riddler™',
    'Thomas Wayne™',
    'Two-Face™\'s Coin',
    'Two-Face™',
    'Utility Belt',
    'Ace the Bat Hound™',
    'Bane™',
    'Bat-Signal™',
    'Batarang™',
    'Batgirl™',
    'Batman™',
    'Batwoman™',
    'Big Barda™',
    'Catwoman™',
    'Commissioner Gordon™',
    'Conner Kent™',
    'Darkseid™',
    'Dove™',
    'Firefly™',
    'Harley Quinn™',
    'Hawk™',
    'Hawkgirl™',
    'Huntress™',
    'Hush™',
    'Jervis Tetch™',
    'Killer Croc™',
    'Mister Miracle™',
    'Mr. Freeze™',
    'Nightwing™',
    'Orion™',
    'Owlman™',
    'Parademon™',
    'Ra\'s Al Ghul™',
    'Red Hood™',
    'Rip Hunter™',
    'Robin™',
    'Talia al Ghul™',
    'The Joker™',
    'The Penguin™',
    'The Question™',
    'The Riddler™',
    'Thomas Wayne™',
    'Two-Face™\'s Coin',
    'Two-Face™',
    'Utility Belt',
    'Ace the Bat Hound™',
    'Bane™',
    'Bat-Signal™',
    'Batarang™',
    'Batgirl™',
    'Batman™',
    'Batwoman™',
    'Big Barda™',
    'Catwoman™',
    'Commissioner Gordon™',
    'Conner Kent™',
    'Dove™',
    'Firefly™',
    'Harley Quinn™',
    'Hawk™',
    'Hawkgirl™',
    'Huntress™',
    'Hush™',
    'Jervis Tetch™',
    'Killer Croc™',
    'Mr. Freeze™',
    'Nightwing™',
    'Orion™',
    'Parademon™',
    'Ra\'s Al Ghul™',
    'Red Hood™',
    'Rip Hunter™',
    'Robin™',
    'Talia al Ghul™',
    'The Penguin™',
    'The Question™',
    'The Riddler™',
    'Thomas Wayne™',
    'Two-Face™\'s Coin',
    'Two-Face™',
    'Utility Belt',
    'Darkseid™',
    'Mister Miracle™',
    'Owlman™',
    'The Joker™',
    'White Lantern Aquaman™',
    'White Lantern Dove™',
    'White Lantern Hal Jordan™',
    'White Lantern Superman™',
);

    public $imw =  array(
    'Howard Stark',
    'Howard Stark',
    'Howard Stark',
    'Hulkbuster Iron Man',
    'Hulkbuster Iron Man',
    'Hulkbuster Iron Man',
    'Iron Manor',
    'Iron Manor',
    'Iron Manor',
    'Iron Spider',
    'Iron Spider',
    'Iron Spider',
    'Jarvis',
    'Jarvis',
    'Jarvis',
    'Rescue',
    'Rescue',
    'Rescue',
    'Space Armor Iron Man',
    'Space Armor Iron Man',
    'Space Armor Iron Man',
    'War Machine',
    'War Machine',
    'War Machine',
    'Armor Wars',
    'Cone of Cold',
    'Hypervelocity',
    'One Against Many',
    'Smash!',
    'Surprise Attack',
    'Upgrade - Fortification',
    'Upgrade - Proton Cannon',
    'Upgrade - Smokescreen',
    'Upgrade - Unibeam',
);
    public $hhs =  array(
    'April',
    'April',
    'April',
    'Casey Jones',
    'Casey Jones',
    'Casey Jones',
    'Donatello',
    'Donatello',
    'Donatello',
    'Foot Ninja',
    'Foot Ninja',
    'Foot Ninja',
    'Hamato Yoshi',
    'Hamato Yoshi',
    'Hamato Yoshi',
    'Karai',
    'Karai',
    'Karai',
    'Leatherhead',
    'Leatherhead',
    'Leatherhead',
    'Leonardo',
    'Leonardo',
    'Leonardo',
    'Metalhead',
    'Metalhead',
    'Metalhead',
    'Michelangelo',
    'Michelangelo',
    'Michelangelo',
    'Raphael',
    'Raphael',
    'Raphael',
    'Renet Tilley',
    'Renet Tilley',
    'Renet Tilley',
    'Shredder',
    'Shredder',
    'Shredder',
    'Slash',
    'Slash',
    'Slash',
    'Tiger Claw',
    'Tiger Claw',
    'Tiger Claw',
    'Triceraton',
    'Triceraton',
    'Triceraton',
    'Haymaker',
    'Ingenious Tactics',
    'Momentum',
    'Mutation',
    'Mysterious Shredder Transport',
    'Nefarious Broadcast',
    'Speedy Delivery',
    'Splinter\'s Teachings',
    'Reclaim',
    'Unstable Canister',
);
    public $dp =  array(
    'Agent Carter',
    'Agent X',
    'Angel Dust',
    'Angela',
    'Black Bolt',
    'Black Tom Cassidy',
    'Blind Al',
    'Bob, Agent of Hydra',
    'Colossus',
    'Deadpool',
    'Dogpool',
    'Domino',
    'Elektra',
    'Evil Deadpool',
    'Fantomex',
    'Flying Car',
    'Free Chimichangas',
    'Hit-Monkey',
    'Kidpool',
    'Lady Bullseye',
    'Lady Deadpool',
    'Lockjaw',
    'M.O.D.O.K.',
    'Madame Hydra',
    'Medusa',
    'Miguel O\'Hara',
    'Mister Sinister',
    'Motorcycle',
    'Multiple Man',
    'Negasonic Teenage Warhead',
    'Outlaw',
    'Sandi Brandenberg',
    'Satchel of Unlimited Weaponry',
    'Scarlet Witch',
    'Shiklah',
    'Stepford Cuckoos',
    'Storm',
    'Taskmaster',
    'Wolverine',
    'X-23',
    'Agent Carter',
    'Agent X',
    'Angel Dust',
    'Angela',
    'Black Bolt',
    'Black Tom Cassidy',
    'Blind Al',
    'Bob, Agent of Hydra',
    'Colossus',
    'Deadpool',
    'Dogpool',
    'Domino',
    'Elektra',
    'Evil Deadpool',
    'Fantomex',
    'Flying Car',
    'Free Chimichangas',
    'Hit-Monkey',
    'Kidpool',
    'Lady Bullseye',
    'Lady Deadpool',
    'Lockjaw',
    'M.O.D.O.K.',
    'Madame Hydra',
    'Medusa',
    'Miguel O\'Hara',
    'Mister Sinister',
    'Motorcycle',
    'Multiple Man',
    'Negasonic Teenage Warhead',
    'Outlaw',
    'Sandi Brandenberg',
    'Satchel of Unlimited Weaponry',
    'Scarlet Witch',
    'Shiklah',
    'Stepford Cuckoos',
    'Storm',
    'Taskmaster',
    'Wolverine',
    'X-23',
    'Agent Carter',
    'Agent X',
    'Angel Dust',
    'Angela',
    'Black Bolt',
    'Black Tom Cassidy',
    'Blind Al',
    'Bob, Agent of Hydra',
    'Colossus',
    'Dogpool',
    'Domino',
    'Elektra',
    'Evil Deadpool',
    'Fantomex',
    'Flying Car',
    'Free Chimichangas',
    'Hit-Monkey',
    'Kidpool',
    'Lady Bullseye',
    'Lockjaw',
    'M.O.D.O.K.',
    'Madame Hydra',
    'Medusa',
    'Miguel O\'Hara',
    'Mister Sinister',
    'Motorcycle',
    'Negasonic Teenage Warhead',
    'Outlaw',
    'Sandi Brandenberg',
    'Satchel of Unlimited Weaponry',
    'Scarlet Witch',
    'Shiklah',
    'Stepford Cuckoos',
    'Storm',
    'Taskmaster',
    'Wolverine',
    'Deadpool',
    'Lady Deadpool',
    'Multiple Man',
    'X-23',
    'Captain America with Mjolnir',
    'Charles Xavier, Juggernaut',
    'Phoenix Force Magneto',
    'Wolverine Lord of Vampires',
);

    public $drs =  array(
    'Ancient One',
    'Ancient One',
    'Ancient One',
    'Clea',
    'Clea',
    'Clea',
    'Doctor Strange',
    'Doctor Strange',
    'Doctor Strange',
    'Dormammu',
    'Dormammu',
    'Dormammu',
    'Eye of Agamotto',
    'Eye of Agamotto',
    'Eye of Agamotto',
    'Mindless Ones',
    'Mindless Ones',
    'Mindless Ones',
    'Scarlet Witch',
    'Scarlet Witch',
    'Scarlet Witch',
    'Wong',
    'Wong',
    'Wong',
);

    public $gaf =  array(
    'Amanda Waller™',
    'Barry Allen™',
    'Batgirl™',
    'Black Adam™',
    'Black Canary™',
    'Captain Cold™',
    'Captain Cold™\'s Cold Gun',
    'Clayface™',
    'Cosmic Treadmill™',
    'Cyborg™',
    'Deadshot™',
    'Deathstroke™',
    'Diggle™',
    'Doctor Light™',
    'Felicity Smoak™',
    'Firestorm™',
    'Giganta™',
    'Gorilla Grodd™',
    'Green Arrow™',
    'Hal Jordan™',
    'Huntress™',
    'Jay Garrick™',
    'Katana™',
    'Killer Frost™',
    'King Shark™',
    'Martian Manhunter™',
    'Merlyn™',
    'Power Ring™',
    'Professor Zoom™',
    'Ra\'s Al Ghul™',
    'Rip Hunter™\'s Chalkboard',
    'Roy Harper™',
    'S.T.A.R. Labs™',
    'Speedy™',
    'Static™',
    'Superman™',
    'The Atom™',
    'Weather Wizard™',
    'Wonder Girl™',
    'Zatanna™',
    'Amanda Waller™',
    'Barry Allen™',
    'Batgirl™',
    'Black Adam™',
    'Black Canary™',
    'Captain Cold™',
    'Captain Cold™\'s Cold Gun',
    'Clayface™',
    'Cosmic Treadmill™',
    'Cyborg™',
    'Deadshot™',
    'Deathstroke™',
    'Diggle™',
    'Doctor Light™',
    'Felicity Smoak™',
    'Firestorm™',
    'Giganta™',
    'Gorilla Grodd™',
    'Green Arrow™',
    'Hal Jordan™',
    'Huntress™',
    'Jay Garrick™',
    'Katana™',
    'Killer Frost™',
    'King Shark™',
    'Martian Manhunter™',
    'Merlyn™',
    'Power Ring™',
    'Professor Zoom™',
    'Ra\'s Al Ghul™',
    'Rip Hunter™\'s Chalkboard',
    'Roy Harper™',
    'S.T.A.R. Labs™',
    'Speedy™',
    'Static™',
    'Superman™',
    'The Atom™',
    'Weather Wizard™',
    'Wonder Girl™',
    'Zatanna™',
    'Amanda Waller™',
    'Batgirl™',
    'Black Adam™',
    'Black Canary™',
    'Captain Cold™',
    'Captain Cold™\'s Cold Gun',
    'Clayface™',
    'Cosmic Treadmill™',
    'Cyborg™',
    'Deadshot™',
    'Deathstroke™',
    'Diggle™',
    'Doctor Light™',
    'Felicity Smoak™',
    'Firestorm™',
    'Giganta™',
    'Gorilla Grodd™',
    'Hal Jordan™',
    'Huntress™',
    'Jay Garrick™',
    'Killer Frost™',
    'King Shark™',
    'Martian Manhunter™',
    'Merlyn™',
    'Power Ring™',
    'Professor Zoom™',
    'Ra\'s Al Ghul™',
    'Rip Hunter™\'s Chalkboard',
    'Roy Harper™',
    'S.T.A.R. Labs™',
    'Speedy™',
    'Static™',
    'Superman™',
    'The Atom™',
    'Weather Wizard™',
    'Wonder Girl™',
    'Barry Allen™',
    'Green Arrow™',
    'Katana™',
    'Zatanna™',
    'White Lantern Batman™',
    'White Lantern Deadman™',
    'White Lantern Sinestro™',
    'White Lantern Wonder Woman™',
);
    public $cw =  array(
    'Black Widow',
    'Black Widow',
    'Black Widow',
    'Captain America',
    'Captain America',
    'Falcon',
    'Falcon',
    'Falcon',
    'Iron Man',
    'Iron Man',
    'Rocket Raccoon',
    'Rocket Raccoon',
    'Rocket Raccoon',
    'Scarlet Spider',
    'Scarlet Spider',
    'Scarlet Spider',
    'She-Hulk',
    'She-Hulk',
    'She-Hulk',
    'Wasp',
    'Wasp',
    'Wasp',
    'Brother Fights Brother',
    'Civil War',
    'Driven Underground',
    'Escape Incarceration',
    'Field Promotion',
    'Internal Dispute',
    'Long Live the Resistance!',
    'Suffering and Satisfaction',
    'Superhero Registration Act',
    'The Front Line',
    'Ant-Man',
    'Baron Zemo',
    'Black Widow',
    'Bullseye',
    'Captain America',
    'Captain Marvel',
    'Deathlok',
    'Falcon',
    'Goliath',
    'Hercules',
    'Iron Fist',
    'Iron Man',
    'Jessica Jones',
    'Justice',
    'Loki',
    'Luke Cage',
    'Maria Hill',
    'Mary Jane',
    'Moon Knight',
    'Moonstone',
    'Ms. Marvel',
    'Namorita',
    'Nitro',
    'Punisher',
    'Pym Particles',
    'Radioactive Man',
    'Rescue',
    'Rocket Raccoon',
    'Ronin',
    'Scarlet Spider',
    'She-Hulk',
    'Songbird',
    'Speedball',
    'Spider-Man',
    'Taskmaster',
    'Thor',
    'Venom',
    'Vibranium Shield',
    'Wasp',
    'Winter Soldier',
    'Ant-Man',
    'Baron Zemo',
    'Bullseye',
    'Captain Marvel',
    'Deathlok',
    'Goliath',
    'Hercules',
    'Iron Fist',
    'Jessica Jones',
    'Justice',
    'Loki',
    'Luke Cage',
    'Maria Hill',
    'Mary Jane',
    'Moon Knight',
    'Moonstone',
    'Ms. Marvel',
    'Namorita',
    'Nitro',
    'Punisher',
    'Pym Particles',
    'Radioactive Man',
    'Rescue',
    'Ronin',
    'Songbird',
    'Speedball',
    'Spider-Man',
    'Taskmaster',
    'Thor',
    'Venom',
    'Vibranium Shield',
    'Winter Soldier',
    'Ant-Man',
    'Baron Zemo',
    'Bullseye',
    'Captain Marvel',
    'Deathlok',
    'Goliath',
    'Hercules',
    'Iron Fist',
    'Jessica Jones',
    'Justice',
    'Loki',
    'Luke Cage',
    'Maria Hill',
    'Mary Jane',
    'Moon Knight',
    'Moonstone',
    'Ms. Marvel',
    'Namorita',
    'Nitro',
    'Punisher',
    'Pym Particles',
    'Radioactive Man',
    'Rescue',
    'Songbird',
    'Speedball',
    'Spider-Man',
    'Taskmaster',
    'Thor',
    'Vibranium Shield',
    'Winter Soldier',
    'Captain America',
    'Iron Man',
    'Ronin',
    'Venom',
    'Natalia Romanova',
    'Shannon Carter',
    'Steve Rogers',
    'Tony Stark',
    'Squirrel Girl',
);

    public $tmnt =  array(
    'April',
    'April',
    'April',
    'Baxter Stockman',
    'Baxter Stockman',
    'Baxter Stockman',
    'Bebop',
    'Bebop',
    'Bebop',
    'Casey Jones',
    'Casey Jones',
    'Casey Jones',
    'Donatello',
    'Donatello',
    'Donatello',
    'Foot Ninja',
    'Foot Ninja',
    'Foot Ninja',
    'Fugitoid',
    'Fugitoid',
    'Fugitoid',
    'Krang',
    'Krang',
    'Krang',
    'Leonardo',
    'Leonardo',
    'Leonardo',
    'Michelangelo',
    'Michelangelo',
    'Michelangelo',
    'Mousers',
    'Mousers',
    'Mousers',
    'Raphael',
    'Raphael',
    'Raphael',
    'Rocksteady',
    'Rocksteady',
    'Rocksteady',
    'Shredder',
    'Shredder',
    'Shredder',
    'Splinter@A',
    'Splinter@A',
    'Splinter@A',
    'Splinter@B',
    'Splinter@B',
    'Splinter@B',
    'Cowabunga!',
    'Enraged',
    'Give Me a Break!',
    'Heroes in a Half-Shell',
    'Lethal Blow',
    'Pizza!',
    'Reckless Abandon',
    'Special Delivery',
    'Tactical Cover',
    'Turtle Van',
);
    public $wko16dd =  array(
    'Strahd'
);
    public $wko16m =  array(
    'Melinda May'
);
    public $wko16dc =  array(
    'Terry McGinnis'
);

    public $wf =  array(
    'Batman™',
    'Batman™',
    'Batman™',
    'Catwoman',
    'Catwoman',
    'Catwoman',
    'Harvey Bullock',
    'Harvey Bullock',
    'Harvey Bullock',
    'Krypto',
    'Krypto',
    'Krypto',
    'Oracle',
    'Oracle',
    'Oracle',
    'Power Girl',
    'Power Girl',
    'Power Girl',
    'Steel',
    'Steel',
    'Steel',
    'Superman™',
    'Superman™',
    'Superman™',
    'Brave Sacrifice',
    'Call to Action',
    'Dark Avenger',
    'End of Days',
    'Kryptonite Threat',
    'Man of Steel',
    'To the Rescue!',
    'Too Big To Fly',
    'Trusted Friend',
    'Vigilante Justice',
    'Alfred Pennyworth',
    'Bane',
    'Batcave',
    'Batgirl',
    'Batman™',
    'Bizarro',
    'Brainiac',
    'Bruce Wayne',
    'Carmine Falcone',
    'Catwoman',
    'Clark Kent',
    'Commissioner Gordon',
    'Dick Grayson',
    'Doomsday',
    'General Zod',
    'Harley Quinn',
    'Harvey Bullock',
    'Kal-L',
    'Krypto',
    'Kryptonite',
    'Lex Luthor',
    'Lois Lane',
    'Mr. Freeze',
    'Mr. Mxyzptlk',
    'Nightwing',
    'Oracle',
    'Poison Ivy',
    'Power Girl',
    'Robin',
    'Scarecrow',
    'Steel',
    'Supergirl',
    'Superman™',
    'Superwoman',
    'The Joker',
    'The Penguin',
    'The Riddler',
    'Two-Face',
    'Ultraman',
    'Wonder Woman',
    'Alfred Pennyworth',
    'Bane',
    'Batcave',
    'Batgirl',
    'Bizarro',
    'Brainiac',
    'Bruce Wayne',
    'Carmine Falcone',
    'Clark Kent',
    'Commissioner Gordon',
    'Dick Grayson',
    'Doomsday',
    'General Zod',
    'Harley Quinn',
    'Kal-L',
    'Kryptonite',
    'Lex Luthor',
    'Lois Lane',
    'Mr. Freeze',
    'Mr. Mxyzptlk',
    'Nightwing',
    'Poison Ivy',
    'Robin',
    'Scarecrow',
    'Supergirl',
    'Superwoman',
    'The Joker',
    'The Penguin',
    'The Riddler',
    'Two-Face',
    'Ultraman',
    'Wonder Woman',
    'Alfred Pennyworth',
    'Bane',
    'Bizarro',
    'Brainiac',
    'Bruce Wayne',
    'Carmine Falcone',
    'Clark Kent',
    'Commissioner Gordon',
    'Dick Grayson',
    'Doomsday',
    'General Zod',
    'Harley Quinn',
    'Kal-L',
    'Kryptonite',
    'Lois Lane',
    'Mr. Freeze',
    'Mr. Mxyzptlk',
    'Nightwing',
    'Poison Ivy',
    'Robin',
    'Scarecrow',
    'Supergirl',
    'Superwoman',
    'The Joker',
    'The Penguin',
    'The Riddler',
    'Two-Face',
    'Wonder Woman',
    'Batcave',
    'Batgirl',
    'Lex Luthor',
    'Ultraman',
    'Black Lantern Anti-Monitor',
    'Black Lantern Firestorm',
    'Black Lantern Green Arrow',
    'Black Lantern Martian Manhunter',
    'Bat-Mite',
);

    public $fus =  array(
    'Bronze Dragon',
    'Bronze Dragon',
    'Bronze Dragon',
    'Cockatrice',
    'Cockatrice',
    'Cockatrice',
    'Glabrezu',
    'Glabrezu',
    'Glabrezu',
    'Gnome Ranger',
    'Gnome Ranger',
    'Gnome Ranger',
    'Half-Elf Bard',
    'Half-Elf Bard',
    'Half-Elf Bard',
    'Hell Hound',
    'Hell Hound',
    'Hell Hound',
    'Hill Giant',
    'Hill Giant',
    'Hill Giant',
    'White Dragon',
    'White Dragon',
    'White Dragon',
    'Banishment',
    'Barkskin',
    'Blink - Transmutation',
    'Chainmail Armor',
    'Cloudkill',
    'Delayed Blast Fireball',
    'Flaming Sword',
    'Mordenkainen\'s Sword',
    'Power Word Kill',
    'Shocking Grasp',
    'Bahamut',
    'Balor',
    'Beholder',
    'Black Dragon',
    'Blink Dog',
    'Bronze Dragon',
    'Bugbear Ambusher',
    'Clay Golem',
    'Cockatrice',
    'Displacer Beast',
    'Drizzt',
    'Dwarf Wizard',
    'Elf Thief',
    'Erinyes',
    'Flesh Golem',
    'Gelatinous Cube',
    'Ghost',
    'Giant Spider',
    'Glabrezu',
    'Gnome Ranger',
    'Goblin',
    'Gorgon',
    'Half-Orc Barbarian',
    'Half-Elf Bard',
    'Hell Hound',
    'Hill Giant',
    'Human Fighter',
    'Intellect Devourer',
    'Iron Golem',
    'Lich',
    'Lizardfolk',
    'Lolth',
    'Oni',
    'Orcus',
    'Potion',
    'Ring',
    'Rust Monster',
    'Storm Giant',
    'White Dragon',
    'Wraith',
    'Bahamut',
    'Balor',
    'Beholder',
    'Black Dragon',
    'Blink Dog',
    'Bugbear Ambusher',
    'Clay Golem',
    'Displacer Beast',
    'Drizzt',
    'Dwarf Wizard',
    'Elf Thief',
    'Erinyes',
    'Flesh Golem',
    'Gelatinous Cube',
    'Ghost',
    'Giant Spider',
    'Goblin',
    'Gorgon',
    'Half-Orc Barbarian',
    'Human Fighter',
    'Intellect Devourer',
    'Iron Golem',
    'Lich',
    'Lizardfolk',
    'Lolth',
    'Oni',
    'Orcus',
    'Potion',
    'Ring',
    'Rust Monster',
    'Storm Giant',
    'Wraith',
    'Bahamut',
    'Balor',
    'Black Dragon',
    'Blink Dog',
    'Clay Golem',
    'Displacer Beast',
    'Dwarf Wizard',
    'Elf Thief',
    'Erinyes',
    'Flesh Golem',
    'Gelatinous Cube',
    'Ghost',
    'Giant Spider',
    'Goblin',
    'Gorgon',
    'Half-Orc Barbarian',
    'Human Fighter',
    'Intellect Devourer',
    'Iron Golem',
    'Lich',
    'Lizardfolk',
    'Lolth',
    'Oni',
    'Orcus',
    'Potion',
    'Rust Monster',
    'Storm Giant',
    'Wraith',
    'Beholder',
    'Bugbear Ambusher',
    'Drizzt',
    'Ring',
    'Deck of Many Things',
    'Hammer of Thunderbolts',
    'Talisman of Ultimate Evil',
    'Robe of the Archmagi',
    'Belaphoss',
);
    public $m2016_dice =  array( 'asm', 'asm', 'asm', 'avx', '', 'cw', 'cw', 'cw', 'cw', 'cw', 'cw' );
    public $m2016 =  array(
    //ASM dice
    'Gwen Stacy',
    'Mary Jane',
    //ASM dice
    'Daredevil',
    //AvX dice
    'Punisher',
    //BAC
    'Villainous Pact',
    //CW dice
    'Ant-Man',
    'Baron Zemo',
    'Ms. Marvel',
    'Loki',
    'Ant-Man',
    'Captain America',
);
    public $d2016 =  array(
    'Mummy',
    'Gelatinous Cube',
    'Half-Dragon',
    'Skeleton',
);

    public $dc2016_dice =  array( 'jl', 'wol', 'wf', 'jl', 'jl', 'wf', '', 'wf', 'wf', '', 'gaf', 'gaf', 'gaf', 'gaf' );
    public $dc2016 =  array(
    // JL dice (not WF)
    'Lex Luthor',
    // WoL dice (not WF)
    'Scarecrow',
    // WF dice (not WoL)
    'Supergirl',
    // JL dice (not WoL)
    'The Flash',
    // JL dice
    'Stargirl',
    // WF dice
    'Lois Lane',
    // BAC
    'Thrown Car',
    // WF dice
    'Mr. Mxyzptlk',
    // WF dice
    'Bizarro',
    // BAC
    'Focus Power',
    // GAF dice
    'Green Arrow™',
    // GAF dice
    'Roy Harper™',
    // GAF dice
    'Barry Allen™',
    // GAF dice
    'Professor Zoom™',
);

    public $asm =  array(
    'Carnage',
    'Carnage',
    'Carnage',
    'Drax',
    'Drax',
    'Drax',
    'Ghost Rider',
    'Ghost Rider',
    'Ghost Rider',
    'Kingpin',
    'Kingpin',
    'Kingpin',
    'Silver Sable',
    'Silver Sable',
    'Silver Sable',
    'Spider-Man',
    'Spider-Man',
    'Spider-Man',
    'Spider-Woman',
    'Spider-Woman',
    'Spider-Woman',
    'White Tiger',
    'White Tiger',
    'White Tiger',
    'Archnemesis!',
    'Back for Seconds!',
    'Betrayal',
    'Exposed!',
    'Great Responsibility',
    'Slander',
    'Spidey\'s Last Stand',
    'True Believer',
    'Web Blast',
    'With Great Power...',
    'Agent Venom',
    'Aunt May',
    'Black Cat',
    'Black Widow',
    'Blade',
    'Blink',
    'Carnage',
    'Cloak',
    'Dagger',
    'Daredevil',
    'Doctor Octopus',
    'Drax',
    'Electro',
    'Firestar',
    'Ghost Rider',
    'Gladiator',
    'Goblin Glider',
    'Green Goblin',
    'Gwen Stacy',
    'Hobgoblin',
    'Hulk',
    'Iceman',
    'Iron Spidey',
    'Kingpin',
    'Kraven the Hunter',
    'Lizard',
    'Luke Cage',
    'Mary Jane',
    'Mysterio',
    'Rhino',
    'Sandman',
    'Scarlet Spider',
    'Silver Sable',
    'Spider-Girl',
    'Spider-Man',
    'Spider-Woman',
    'Vulture',
    'Web Shooters',
    'White Tiger',
    'Wolverine',
    'Agent Venom',
    'Aunt May',
    'Black Cat',
    'Black Widow',
    'Blade',
    'Blink',
    'Cloak',
    'Dagger',
    'Daredevil',
    'Doctor Octopus',
    'Electro',
    'Firestar',
    'Gladiator',
    'Goblin Glider',
    'Green Goblin',
    'Gwen Stacy',
    'Hobgoblin',
    'Hulk',
    'Iceman',
    'Iron Spidey',
    'Kraven the Hunter',
    'Lizard',
    'Luke Cage',
    'Mary Jane',
    'Mysterio',
    'Rhino',
    'Sandman',
    'Scarlet Spider',
    'Spider-Girl',
    'Vulture',
    'Web Shooters',
    'Wolverine',
    'Agent Venom',
    'Aunt May',
    'Black Widow',
    'Blade',
    'Blink',
    'Cloak',
    'Dagger',
    'Daredevil',
    'Doctor Octopus',
    'Electro',
    'Firestar',
    'Gladiator',
    'Goblin Glider',
    'Green Goblin',
    'Gwen Stacy',
    'Hobgoblin',
    'Iceman',
    'Kraven the Hunter',
    'Lizard',
    'Luke Cage',
    'Mary Jane',
    'Mysterio',
    'Rhino',
    'Sandman',
    'Scarlet Spider',
    'Vulture',
    'Web Shooters',
    'Wolverine',
    'Black Cat',
    'Hulk',
    'Iron Spidey',
    'Spider-Girl',
    'Green Goblin@Z',
    'Kingpin@Z',
    'Morbius@Z',
    'Venom@Z',
);
    public $m2015 =  array(
    'Ultron',
    'Nova',
    'Thanos',
    'Iron Fist',
);

    public $wolop =  array(
    'Robin',
    'Starfire',
    'Batmobile',
);
    public $wol =  array(
    'Anti-Monitor',
    'Anti-Monitor',
    'Anti-Monitor',
    'Batman™',
    'Batman™',
    'Batman™',
    'Guy Gardner',
    'Guy Gardner',
    'Guy Gardner',
    'Hal Jordan',
    'Hal Jordan',
    'Hal Jordan',
    'John Stewart',
    'John Stewart',
    'John Stewart',
    'Kyle Rayner',
    'Kyle Rayner',
    'Kyle Rayner',
    'Lex Luthor',
    'Lex Luthor',
    'Lex Luthor',
    'Sinestro',
    'Sinestro',
    'Sinestro',
    'Big Entrance',
    'Enormous Destruction',
    'Heroic Defense',
    'Lethal Force',
    'Monument to Evil',
    'Relaxing',
    'Stealth Ops',
    'Vicious Struggle',
    'Fighting',
    'You\'ve Been Chosen',
    'Anti-Monitor',
    'Atom',
    'Atrocitus',
    'Batman™',
    'Beast Boy',
    'Bleez',
    'Carol Ferris',
    'Dex-Starr',
    'Fatality',
    'The Flash',
    'Guy Gardner',
    'Hal Jordan',
    'Indigo-1',
    'Jade',
    'John Stewart',
    'Kilowog',
    'Kyle Rayner',
    'Lantern Battery',
    'Lantern Ring',
    'Larfleeze',
    'Lex Luthor',
    'Lyssa Drak',
    'Mera',
    'Miri Riam',
    'Mogo',
    'Mongul',
    'Munk',
    'Parallax',
    'Ranx',
    'Raven',
    'Saint Walker',
    'Scarecrow',
    'Sinestro',
    'Spectre',
    'Starfire',
    'Superboy Prime',
    'Supergirl',
    'Warth',
    'Wonder Girl',
    'Wonder Woman',
    'Atom',
    'Atrocitus',
    'Beast Boy',
    'Bleez',
    'Carol Ferris',
    'Dex-Starr',
    'Fatality',
    'The Flash',
    'Indigo-1',
    'Jade',
    'Kilowog',
    'Lantern Battery',
    'Lantern Ring',
    'Larfleeze',
    'Lyssa Drak',
    'Mera',
    'Miri Riam',
    'Mogo',
    'Mongul',
    'Munk',
    'Parallax',
    'Ranx',
    'Raven',
    'Saint Walker',
    'Scarecrow',
    'Spectre',
    'Starfire',
    'Superboy Prime',
    'Supergirl',
    'Warth',
    'Wonder Girl',
    'Wonder Woman',
    'Atom',
    'Atrocitus',
    'Beast Boy',
    'Bleez',
    'Carol Ferris',
    'Dex-Starr',
    'Fatality',
    'The Flash',
    'Indigo-1',
    'Jade',
    'Kilowog',
    'Lantern Ring',
    'Larfleeze',
    'Lyssa Drak',
    'Mera',
    'Miri Riam',
    'Mogo',
    'Mongul',
    'Munk',
    'Ranx',
    'Raven',
    'Saint Walker',
    'Scarecrow',
    'Spectre',
    'Superboy Prime',
    'Supergirl',
    'Warth',
    'Wonder Girl',
    'Lantern Battery',
    'Parallax',
    'Starfire',
    'Wonder Woman',
    'Black Lantern Aquaman',
    'Black Lantern Batman™',
    'Black Lantern Superman™',
    'Black Lantern Wonder Woman',
);
    public $aou =  array(
    'Black Widow',
    'Black Widow',
    'Black Widow',
    'Captain America',
    'Captain America',
    'Captain America',
    'Hawkeye',
    'Hawkeye',
    'Hawkeye',
    'Hulk',
    'Hulk',
    'Hulk',
    'Iron Man',
    'Iron Man',
    'Iron Man',
    'Thor',
    'Thor',
    'Thor',
    'Ultron',
    'Ultron',
    'Ultron',
    'Vision',
    'Vision',
    'Vision',
    'Assemble!',
    'Call Them Out!',
    'Coordinated Strike',
    'Enslavement',
    'Hulk Out',
    'Infiltrate',
    'Nasty Plot',
    'Ready to Rocket!',
    'Surprise Attack',
    'The Oppression Begins',
    'Baron Zemo',
    'Beast',
    'Black Widow',
    'Bucky',
    'Captain America',
    'Captain Marvel',
    'Captain Universe',
    'Daredevil',
    'Enchantress',
    'Gamora',
    'Giant Man',
    'Groot',
    'Hawkeye',
    'Hulk',
    'Hyperion',
    'Iron Man',
    'Jocasta',
    'Kang',
    'Loki',
    'Loki\'s Scepter',
    'Maria Hill',
    'Moondragon',
    'Nick Fury',
    'Odin',
    'Pepper Potts',
    'Phil Coulson',
    'Red Skull',
    'Rocket Raccoon',
    'S.H.I.E.L.D. Agent',
    'S.H.I.E.L.D. Helicarrier',
    'Spider-Woman',
    'Starhawk',
    'Star-Lord',
    'Thanos',
    'Thor',
    'Ultron',
    'Ultron Drone',
    'Vision',
    'Wasp',
    'Wonder Man',
    'Baron Zemo',
    'Beast',
    'Bucky',
    'Captain Marvel',
    'Captain Universe',
    'Daredevil',
    'Enchantress',
    'Gamora',
    'Giant Man',
    'Groot',
    'Hyperion',
    'Jocasta',
    'Kang',
    'Loki',
    'Loki\'s Scepter',
    'Maria Hill',
    'Moondragon',
    'Nick Fury',
    'Odin',
    'Pepper Potts',
    'Phil Coulson',
    'Red Skull',
    'Rocket Raccoon',
    'S.H.I.E.L.D. Agent',
    'S.H.I.E.L.D. Helicarrier',
    'Spider-Woman',
    'Starhawk',
    'Star-Lord',
    'Thanos',
    'Ultron Drone',
    'Wasp',
    'Wonder Man',
    'Baron Zemo',
    'Beast',
    'Bucky',
    'Captain Marvel',
    'Daredevil',
    'Enchantress',
    'Gamora',
    'Giant Man',
    'Hyperion',
    'Kang',
    'Loki',
    'Loki\'s Scepter',
    'Maria Hill',
    'Moondragon',
    'Nick Fury',
    'Odin',
    'Pepper Potts',
    'Phil Coulson',
    'Red Skull',
    'Rocket Raccoon',
    'S.H.I.E.L.D. Agent',
    'S.H.I.E.L.D. Helicarrier',
    'Spider-Woman',
    'Starhawk',
    'Star-Lord',
    'Ultron Drone',
    'Wasp',
    'Wonder Man',
    'Captain Universe',
    'Groot',
    'Jocasta',
    'Thanos',
    'Magneto@Z',
    'Red Skull@Z',
    'Gladiator@Z',
    'Electro@Z',
);

    public $dctw =  array(
    'Pandora\'s Box',
    'Superman™',
    'House of Mystery',
    'Constantine',
    'Wonder Woman',
    'Shazam!',
    'Martian Manhunter',
    'Firestorm',
    'The Outsider',
    'Batman™',
    'Atomica',
);
    public $jl =  array(
    'Batman™',
    'Batman™',
    'Batman™',
    'Darkseid',
    'Darkseid',
    'Darkseid',
    'Deathstroke',
    'Deathstroke',
    'Deathstroke',
    'Green Arrow',
    'Green Arrow',
    'Green Arrow',
    'Martian Manhunter',
    'Martian Manhunter',
    'Martian Manhunter',
    'Superman™',
    'Superman™',
    'Superman™',
    'Wonder Woman',
    'Wonder Woman',
    'Wonder Woman',
    'Zatanna',
    'Zatanna',
    'Zatanna',
    'Anger Issues',
    'Casualties',
    'Fist of Fury',
    'Phantom Zone',
    'Pick Your Battles',
    'Righteous Charge',
    'Save Civilians',
    'Shockwave',
    'Villainous Pact',
    'Vulnerability',
    'Aquaman',
    'The Atom',
    'Batarang',
    'Batman™',
    'Black Manta',
    'Blue Beetle',
    'Booster Gold',
    'Brainiac',
    'Captain Cold',
    'Catwoman',
    'Cheetah',
    'Constantine',
    'Cyborg',
    'Darkseid',
    'Deadman',
    'Deathstroke',
    'Firestorm',
    'The Flash',
    'Green Arrow',
    'Green Lantern',
    'Harley Quinn',
    'Hawkman',
    'The Joker',
    'Katana',
    'Lantern Power Ring',
    'Lex Luthor',
    'Martian Manhunter',
    'Red Tornado',
    'Robin',
    'Shazam!',
    'Sinestro',
    'Solomon Grundy',
    'Stargirl',
    'Superman™',
    'Swamp Thing',
    'Vibe',
    'Vixen',
    'Wonder Woman',
    'Zatanna',
    'Aquaman',
    'The Atom',
    'Batarang',
    'Black Canary',
    'Black Manta',
    'Blue Beetle',
    'Booster Gold',
    'Brainiac',
    'Captain Cold',
    'Cheetah',
    'Constantine',
    'Cyborg',
    'Deadman',
    'Firestorm',
    'The Flash',
    'Green Lantern',
    'Harley Quinn',
    'Hawkman',
    'The Joker',
    'Katana',
    'Lantern Power Ring',
    'Lex Luthor',
    'Red Tornado',
    'Robin',
    'Shazam!',
    'Sinestro',
    'Solomon Grundy',
    'Stargirl',
    'Swamp Thing',
    'Vibe',
    'Vixen',
    'The Atom',
    'Aquaman',
    'Batarang',
    'Black Canary',
    'Black Manta',
    'Blue Beetle',
    'Booster Gold',
    'Brainiac',
    'Captain Cold',
    'Catwoman',
    'Cheetah',
    'Cyborg',
    'Deadman',
    'Firestorm',
    'Green Lantern',
    'Harley Quinn',
    'Hawkman',
    'The Joker',
    'Katana',
    'Lantern Power Ring',
    'Lex Luthor',
    'Red Tornado',
    'Robin',
    'Shazam!',
    'Sinestro',
    'Solomon Grundy',
    'Stargirl',
    'Swamp Thing',
    'Vibe',
    'Vixen',
    'Black Canary',
    'Catwoman',
    'Constantine',
    'The Flash',
);
    public $ygo =  array(
    'Blue-Eyes White Dragon',
    'Celtic Guardian',
    'Dark Magician',
    'Harpie Lady',
    'Kuriboh',
    'La Jinn the Mystical Genie of the Lamp',
    'Red-Eyes B. Dragon',
    'Time Wizard',
    'Baby Dragon',
    'Black Luster Soldier',
    'Blade Knight',
    'Blue-Eyes White Dragon',
    'Breaker the Magical Warrior',
    'Buster Blader',
    'Celtic Guardian',
    'Curse of Dragon',
    'Dark Magician',
    'Dark Magician Girl',
    'Doomcaliber Knight',
    'Flame Swordsman',
    'Gaia the Fierce Knight',
    'Goblin Attack Force',
    'Harpie Lady',
    'Harpie Lady Sisters',
    'Injection Fairy Lily',
    'Jinzo',
    'Kuriboh',
    'La Jinn the Mystical Genie of the Lamp',
    'Lord of D.',
    'Man-Eater Bug',
    'Marshmallon',
    'Morphing Jar',
    'Mystical Elf',
    'Red-Eyes B. Dragon',
    'Ring of Magnetism',
    'Saggi the Dark Clown',
    'Sangan',
    'Summoned Skull',
    'Time Wizard',
    'Trap Hole',
    'Baby Dragon',
    'Black Luster Soldier',
    'Blade Knight',
    'Breaker the Magical Warrior',
    'Buster Blader',
    'Curse of Dragon',
    'Dark Magician Girl',
    'Doomcaliber Knight',
    'Flame Swordsman',
    'Gaia the Fierce Knight',
    'Goblin Attack Force',
    'Harpie Lady Sisters',
    'Injection Fairy Lily',
    'Jinzo',
    'Lord of D.',
    'Man-Eater Bug',
    'Marshmallon',
    'Millennium Puzzle',
    'Millennium Rod',
    'Morphing Jar',
    'Mystical Elf',
    'Obelisk the Tormentor',
    'Ring of Magnetism',
    'Saggi the Dark Clown',
    'Sangan',
    'Slifer the Sky Dragon',
    'Summoned Skull',
    'Thousand Dragon',
    'Trap Hole',
    'The Winged Dragon of Ra',
    'Baby Dragon',
    'Black Luster Soldier',
    'Blade Knight',
    'Blue-Eyes White Dragon',
    'Breaker the Magical Warrior',
    'Buster Blader',
    'Celtic Guardian',
    'Curse of Dragon',
    'Dark Magician',
    'Dark Magician Girl',
    'Doomcaliber Knight',
    'Flame Swordsman',
    'Gaia the Fierce Knight',
    'Goblin Attack Force',
    'Harpie Lady',
    'Harpie Lady Sisters',
    'Injection Fairy Lily',
    'Jinzo',
    'Kuriboh',
    'La Jinn the Mystical Genie of the Lamp',
    'Lord of D.',
    'Man-Eater Bug',
    'Marshmallon',
    'Morphing Jar',
    'Mystical Elf',
    'Obelisk the Tormentor',
    'Red-Eyes B. Dragon',
    'Ring of Magnetism',
    'Saggi the Dark Clown',
    'Sangan',
    'Slifer the Sky Dragon',
    'Summoned Skull',
    'Thousand Dragon',
    'Time Wizard',
    'Trap Hole',
    'The Winged Dragon of Ra',
    'Obelisk the Tormentor',
    'Slifer the Sky Dragon',
    'Thousand Dragon',
    'The Winged Dragon of Ra',
    'Change of Heart',
    'Crush Card Virus',
    'Horn of the Unicorn',
    'Mirror Force',
    'Mirror Wall',
    'Monster Reborn',
    'Mystic Box',
    'Spellbinding Circle',
    'Swords of Revealing Light',
    'Waboku',
);
    public $uxmop2 =  array(
    'Hawkeye',
    'Scarlet Witch',
    'She-Hulk',
);
    public $uxmop =  array(
    'Magneto',
    'Apocalypse',
    'Beast',
    'Sentinel',
    'Kitty Pryde',
    'Wolverine',
    'Marvel Girl',
    'Emma Frost',
    'Phoenix',
);
    public $uxm =  array(
    'Angel',
    'Angel',
    'Angel',
    'Cyclops',
    'Cyclops',
    'Cyclops',
    'Iceman',
    'Iceman',
    'Iceman',
    'Juggernaut',
    'Juggernaut',
    'Juggernaut',
    'Kitty Pryde',
    'Kitty Pryde',
    'Kitty Pryde',
    'Magneto',
    'Magneto',
    'Magneto',
    'Quicksilver',
    'Quicksilver',
    'Quicksilver',
    'Wolverine',
    'Wolverine',
    'Wolverine',
    'Ambush',
    'Enrage',
    'Feedback',
    'Imprisoned',
    'Possession',
    'Reckless Melee',
    'Relentless',
    'Selective Shield',
    'Take That, Villain!',
    'Transfer Power',
    'Ant-Man',
    'Apocalypse',
    'Bishop',
    'Black Panther',
    'Cable',
    'Captain America',
    'Emma Frost',
    'Falcon',
    'Iron Man',
    'Magik',
    'Marvel Girl',
    'Mister Sinister',
    'Mystique',
    'Namor',
    'Professor X',
    'Psylocke',
    'Pyro',
    'Red Hulk',
    'Sabretooth',
    'Scarlet Witch',
    'Sentinel',
    'She-Hulk',
    'Spider-Man',
    'Storm',
    'Toad',
    'Vision',
    'X-23',
    'Cerebro',
    'Angel',
    'Ant-Man',
    'Apocalypse',
    'Bishop',
    'Black Panther',
    'Cable',
    'Captain America',
    'Cyclops',
    'Falcon',
    'Iceman',
    'Juggernaut',
    'Kitty Pryde',
    'Magik',
    'Magneto',
    'Marvel Girl',
    'Mister Sinister',
    'Mystique',
    'Namor',
    'Professor X',
    'Psylocke',
    'Pyro',
    'Quicksilver',
    'Red Hulk',
    'Sabretooth',
    'Sentinel',
    'She-Hulk',
    'Storm',
    'Toad',
    'Vision',
    'Wolverine',
    'X-23',
    'Cerebro',
    'Ant-Man',
    'Apocalypse',
    'Bishop',
    'Black Panther',
    'Cable',
    'Captain America',
    'Emma Frost',
    'Falcon',
    'Iron Man',
    'Magik',
    'Marvel Girl',
    'Mister Sinister',
    'Mystique',
    'Namor',
    'Professor X',
    'Psylocke',
    'Pyro',
    'Red Hulk',
    'Sabretooth',
    'Scarlet Witch',
    'Sentinel',
    'She-Hulk',
    'Spider-Man',
    'Storm',
    'Toad',
    'Vision',
    'X-23',
    'Cerebro',
    'Emma Frost',
    'Iron Man',
    'Scarlet Witch',
    'Spider-Man',
);
    public $avxop =  array(
    'Teamwork',
    'Rally!',
    'Deflection',
    'Teleport',
    'Collateral Damage',
    'Takedown',
    'Thor',
    'Spider-Man',
    'Wolverine',
    'Colossus',
    'Iron Man',
    'Cyclops',
    'Phoenix Force',
);
    public $avx =  array(
    'Beast',
    'Beast',
    'Beast',
    'Captain America',
    'Captain America',
    'Captain America',
    'Hulk',
    'Hulk',
    'Hulk',
    'Human Torch',
    'Human Torch',
    'Human Torch',
    'Iron Man',
    'Iron Man',
    'Iron Man',
    'Spider-Man',
    'Spider-Man',
    'Spider-Man',
    'Storm',
    'Storm',
    'Storm',
    'Thor',
    'Thor',
    'Thor',
    'Distraction',
    'Focus Power',
    'Force Beam',
    'Gearing Up',
    'Inner Rage',
    'Invulnerability',
    'Power Bolt',
    'Smash!',
    'Take Cover',
    'Thrown Car',
    'Angel',
    'Black Widow',
    'Colossus',
    'Cyclops',
    'Deadpool',
    'Doctor Doom',
    'Doctor Octopus',
    'Doctor Strange',
    'Gambit',
    'Ghost Rider',
    'Green Goblin',
    'Hawkeye',
    'Loki',
    'Magneto',
    'Mr. Fantastic',
    'Mystique',
    'Nick Fury',
    'Nightcrawler',
    'Nova',
    'Phoenix',
    'Professor X',
    'Punisher',
    'Rogue',
    'Silver Surfer',
    'Thing',
    'Venom',
    'War Machine',
    'Wolverine',
    'Mjolnir',
    'Vibranium Shield',
    'Angel',
    'Beast',
    'Captain America',
    'Colossus',
    'Cyclops',
    'Deadpool',
    'Doctor Doom',
    'Doctor Octopus',
    'Doctor Strange',
    'Gambit',
    'Ghost Rider',
    'Hawkeye',
    'Hulk',
    'Human Torch',
    'Iron Man',
    'Loki',
    'Magneto',
    'Mystique',
    'Nick Fury',
    'Nightcrawler',
    'Nova',
    'Phoenix',
    'Professor X',
    'Punisher',
    'Rogue',
    'Silver Surfer',
    'Spider-Man',
    'Storm',
    'Thing',
    'Thor',
    'Venom',
    'War Machine',
    'Mjolnir',
    'Vibranium Shield',
    'Angel',
    'Black Widow',
    'Colossus',
    'Cyclops',
    'Deadpool',
    'Doctor Doom',
    'Doctor Octopus',
    'Doctor Strange',
    'Gambit',
    'Ghost Rider',
    'Green Goblin',
    'Hawkeye',
    'Loki',
    'Magneto',
    'Mr. Fantastic',
    'Mystique',
    'Nick Fury',
    'Nightcrawler',
    'Nova',
    'Phoenix',
    'Professor X',
    'Punisher',
    'Rogue',
    'Silver Surfer',
    'Thing',
    'Venom',
    'War Machine',
    'Wolverine',
    'Mjolnir',
    'Vibranium Shield',
    'Black Widow',
    'Green Goblin',
    'Mr. Fantastic',
    'Wolverine',
);
    public $bff =  array(
    'Beholder',
    'Beholder',
    'Beholder',
    'Blue Dragon',
    'Blue Dragon',
    'Blue Dragon',
    'Gelatinous Cube',
    'Gelatinous Cube',
    'Gelatinous Cube',
    'Green Dragon',
    'Green Dragon',
    'Green Dragon',
    'Halfling Thief',
    'Halfling Thief',
    'Halfling Thief',
    'Human Paladin',
    'Human Paladin',
    'Human Paladin',
    'Troll',
    'Troll',
    'Troll',
    'Vampire',
    'Vampire',
    'Vampire',
    'Beholder',
    'Blue Dragon',
    'Carrion Crawler',
    'Copper Dragon',
    'Dracolich',
    'Drow Assassin',
    'Dwarf Cleric',
    'Elf Wizard',
    'Frost Giant',
    'Gelatinous Cube',
    'Green Dragon',
    'Half-Dragon',
    'Half-Orc Fighter',
    'Halfling Thief',
    'Human Paladin',
    'Invisible Stalker',
    'Kobold',
    'Manticore',
    'Mind Flayer',
    'Minotaur',
    'Mummy',
    'Orc',
    'Owlbear',
    'Pit Fiend',
    'Purple Worm',
    'Red Dragon',
    'Skeleton',
    'Stirge',
    'Tarrasque',
    'Treant',
    'Troll',
    'Umber Hulk',
    'Unicorn',
    'Vampire',
    'Wererat',
    'Zombie',
    'Magic Helmet',
    'Magic Sword',
    'Limited Wish',
    'Prismatic Spray',
    'Carrion Crawler',
    'Copper Dragon',
    'Dracolich',
    'Drow Assassin',
    'Dwarf Cleric',
    'Elf Wizard',
    'Frost Giant',
    'Half-Dragon',
    'Half-Orc Fighter',
    'Invisible Stalker',
    'Kobold',
    'Manticore',
    'Mind Flayer',
    'Minotaur',
    'Mummy',
    'Orc',
    'Owlbear',
    'Pit Fiend',
    'Purple Worm',
    'Red Dragon',
    'Skeleton',
    'Stirge',
    'Tarrasque',
    'Treant',
    'Umber Hulk',
    'Unicorn',
    'Wererat',
    'Zombie',
    'Magic Helmet',
    'Magic Sword',
    'Limited Wish',
    'Prismatic Spray',
    'Carrion Crawler',
    'Copper Dragon',
    'Dracolich',
    'Drow Assassin',
    'Dwarf Cleric',
    'Elf Wizard',
    'Frost Giant',
    'Half-Dragon',
    'Half-Orc Fighter',
    'Invisible Stalker',
    'Kobold',
    'Manticore',
    'Minotaur',
    'Mummy',
    'Orc',
    'Owlbear',
    'Pit Fiend',
    'Purple Worm',
    'Skeleton',
    'Treant',
    'Umber Hulk',
    'Unicorn',
    'Wererat',
    'Zombie',
    'Magic Helmet',
    'Magic Sword',
    'Limited Wish',
    'Prismatic Spray',
    'Mind Flayer',
    'Red Dragon',
    'Stirge',
    'Tarrasque',
    'Blessing',
    'Charm',
    'Cone of Cold',
    'Dimension Door',
    'Finger of Death',
    'Fireball',
    'Magic Missile',
    'Polymorph',
    'Resurrection',
    'Stinking Cloud',
);
    public $bff_promo =  array(
    'Minsc and Boo',
);
    public $bff_op =  array(
    'Drow Assassin',
    'Elf Wizard',
    'Dwarf Cleric',
    'Halfling Thief',
    'Treant',
    'Copper Dragon',
    'Zombie',
    'Owlbear',
    'Green Dragon',
);



}